version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my/php
    container_name: app<project-number>
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./supervisor/app.conf:/etc/supervisor/conf.d/app.conf

    networks:
      - app<project-number>-network
      - mysql_app-network
      - redis_app-network
      - mailhog_app-network

  #Nginx Service
  webserver:
    
    image: nginx:alpine
    container_name: webserver<project-number>
    restart: unless-stopped
    tty: true
    ports:
        - "3006:80"
    volumes:
        - ./app:/var/www
        - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
        - app<project-number>-network

#Docker Networks
networks:
  app<project-number>-network:
    driver: bridge
  mysql_app-network:
    external: true
  redis_app-network:
    external: true
  mailhog_app-network:
    external: true
